// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:7a326246-6d04-434a-833b-438ca694b539",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_DSYD5ZSBE",
    "aws_user_pools_web_client_id": "7s8gkv5qq53ekjked5jvb1k5lt"
};


export default awsmobile;
